from pymongo import MongoClient
from datetime import datetime
from config import MONGO_URI

# Connect to MongoDB
client = MongoClient(MONGO_URI)
db = client.utsavdarshan

# Mumbai pandal data - 50 popular Ganesh pandals
mumbai_pandals = [
    {
        "name": "Lalbaugcha Raja",
        "description": "Most famous Ganesh pandal in Mumbai, known for its massive idol and wish-fulfilling legacy",
        "address": "Lalbaug Market, G. D. Ambedkar Marg, Lalbaug, Parel",
        "area": "Lalbaug",
        "location": {"type": "Point", "coordinates": [72.8777, 18.9974]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2471 1883",
        "theme": "Traditional Royal",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "GSB Seva Mandal",
        "description": "Known for its gold and silver decorations and eco-friendly celebrations",
        "address": "King's Circle, Matunga East",
        "area": "Matunga",
        "location": {"type": "Point", "coordinates": [72.8558, 19.0277]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2404 5673",
        "theme": "Eco-friendly",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Andhericha Raja",
        "description": "Famous Ganesh pandal in western suburbs known for creative themes",
        "address": "Azad Nagar, Veera Desai Road, Andheri West",
        "area": "Andheri",
        "location": {"type": "Point", "coordinates": [72.8432, 19.1208]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2624 8546",
        "theme": "Social Awareness",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Mumbaicha Raja",
        "description": "Known for its grand decorations and social messages",
        "address": "Ganesh Gully, Lalbaug",
        "area": "Lalbaug",
        "location": {"type": "Point", "coordinates": [72.8815, 18.9982]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2374 2234",
        "theme": "Social Message",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Chinchpoklicha Chintamani",
        "description": "Historic pandal known for traditional celebrations",
        "address": "Chinchpokli Bridge, Chinchpokli",
        "area": "Chinchpokli",
        "location": {"type": "Point", "coordinates": [72.8833, 18.9900]},
        "opening_time": "06:00",
        "closing_time": "22:00",
        "contact": "+91 22 2377 8899",
        "theme": "Traditional",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Girgaoncha Raja",
        "description": "Famous for its artistic decorations and cultural activities",
        "address": "Girgaon Chowpatty",
        "area": "Girgaon",
        "location": {"type": "Point", "coordinates": [72.8154, 18.9520]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2386 7755",
        "theme": "Cultural Heritage",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Khetwadi Cha Raja",
        "description": "Known for its tall Ganesh idols and elaborate decorations",
        "address": "12th Lane, Khetwadi",
        "area": "Khetwadi",
        "location": {"type": "Point", "coordinates": [72.8188, 18.9561]},
        "opening_time": "07:00",
        "closing_time": "23:00",
        "contact": "+91 22 2387 4455",
        "theme": "Majestic Height",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Fort Vibhag Sarvajanik Ganeshotsav Mandal",
        "description": "Historic pandal in Mumbai's business district",
        "address": "Fort Area",
        "area": "Fort",
        "location": {"type": "Point", "coordinates": [72.8347, 18.9345]},
        "opening_time": "07:00",
        "closing_time": "21:00",
        "contact": "+91 22 2261 3344",
        "theme": "Heritage",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Sahyadri Krida Mandal",
        "description": "Popular pandal known for its environmental themes",
        "address": "Chembur Colony",
        "area": "Chembur",
        "location": {"type": "Point", "coordinates": [72.8994, 19.0530]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2522 6677",
        "theme": "Environmental",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Bandra Cha Raja",
        "description": "Popular pandal in suburban Mumbai",
        "address": "S V Road, Bandra West",
        "area": "Bandra",
        "location": {"type": "Point", "coordinates": [72.8411, 19.0596]},
        "opening_time": "07:00",
        "closing_time": "22:30",
        "contact": "+91 22 2642 5588",
        "theme": "Modern Art",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Powai Sarvajanik Ganeshotsav Mandal",
        "description": "Known for its tech-themed decorations",
        "address": "Hiranandani Gardens, Powai",
        "area": "Powai",
        "location": {"type": "Point", "coordinates": [72.9088, 19.1196]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2857 1122",
        "theme": "Technology",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Vikhroli Cha Raja",
        "description": "Community pandal known for social service",
        "address": "Vikhroli West",
        "area": "Vikhroli",
        "location": {"type": "Point", "coordinates": [72.9277, 19.1109]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2574 9900",
        "theme": "Social Service",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Ghatkopar Cha Raja",
        "description": "Famous for its artistic themes",
        "address": "60 Feet Road, Ghatkopar East",
        "area": "Ghatkopar",
        "location": {"type": "Point", "coordinates": [72.9082, 19.0858]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2506 7788",
        "theme": "Artistic",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Borivali Cha Raja",
        "description": "Popular pandal in western suburbs",
        "address": "IC Colony, Borivali West",
        "area": "Borivali",
        "location": {"type": "Point", "coordinates": [72.8564, 19.2312]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2893 4455",
        "theme": "Community Spirit",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Kandivali Cha Raja",
        "description": "Known for its cultural programs",
        "address": "Mahavir Nagar, Kandivali West",
        "area": "Kandivali",
        "location": {"type": "Point", "coordinates": [72.8472, 19.2006]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2868 5566",
        "theme": "Cultural",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Malad Cha Raja",
        "description": "Popular for its youth activities",
        "address": "S V Road, Malad West",
        "area": "Malad",
        "location": {"type": "Point", "coordinates": [72.8424, 19.1858]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2844 7788",
        "theme": "Youth Empowerment",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Dahisar Cha Raja",
        "description": "Known for environmental awareness",
        "address": "Dahisar East",
        "area": "Dahisar",
        "location": {"type": "Point", "coordinates": [72.8611, 19.2489]},
        "opening_time": "07:00",
        "closing_time": "21:30",
        "contact": "+91 22 2828 9900",
        "theme": "Environmental",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Mulund Cha Raja",
        "description": "Famous for its modern themes",
        "address": "Mulund West",
        "area": "Mulund",
        "location": {"type": "Point", "coordinates": [72.9469, 19.1724]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2564 3322",
        "theme": "Modern",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Kurla Cha Raja",
        "description": "Known for its traditional celebrations",
        "address": "LBS Marg, Kurla West",
        "area": "Kurla",
        "location": {"type": "Point", "coordinates": [72.8879, 19.0724]},
        "opening_time": "06:00",
        "closing_time": "22:30",
        "contact": "+91 22 2512 4433",
        "theme": "Traditional",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Tilak Nagar Cha Raja",
        "description": "Community pandal with social message",
        "address": "Tilak Nagar, Chembur",
        "area": "Tilak Nagar",
        "location": {"type": "Point", "coordinates": [72.8994, 19.0530]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2527 8899",
        "theme": "Social Message",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Sion Cha Raja",
        "description": "Known for its artistic decorations",
        "address": "Sion Circle",
        "area": "Sion",
        "location": {"type": "Point", "coordinates": [72.8686, 19.0379]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2407 6655",
        "theme": "Artistic",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Wadala Cha Raja",
        "description": "Known for its innovative themes and community involvement",
        "address": "Wadala East",
        "area": "Wadala",
        "location": {"type": "Point", "coordinates": [72.8627, 19.0178]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2415 7788",
        "theme": "Innovation",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Worli Cha Raja",
        "description": "Sea-facing pandal with beautiful decorations",
        "address": "Worli Seaface",
        "area": "Worli",
        "location": {"type": "Point", "coordinates": [72.8175, 19.0096]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2494 6633",
        "theme": "Marine Life",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Parel Cha Raja",
        "description": "Historic pandal in mill area",
        "address": "Parel East",
        "area": "Parel",
        "location": {"type": "Point", "coordinates": [72.8412, 18.9977]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2412 9900",
        "theme": "Industrial Heritage",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Lower Parel Sarvajanik Ganeshotsav",
        "description": "Modern pandal with corporate support",
        "address": "Lower Parel West",
        "area": "Lower Parel",
        "location": {"type": "Point", "coordinates": [72.8275, 18.9939]},
        "opening_time": "07:00",
        "closing_time": "22:30",
        "contact": "+91 22 2496 5544",
        "theme": "Modern Art",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Goregaon Cha Raja",
        "description": "Popular suburban pandal with film city theme",
        "address": "Film City Road, Goregaon East",
        "area": "Goregaon",
        "location": {"type": "Point", "coordinates": [72.8697, 19.1663]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2876 3322",
        "theme": "Bollywood",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Santacruz Cha Raja",
        "description": "Known for its youth-focused activities",
        "address": "Santacruz West",
        "area": "Santacruz",
        "location": {"type": "Point", "coordinates": [72.8424, 19.0849]},
        "opening_time": "07:00",
        "closing_time": "22:30",
        "contact": "+91 22 2649 8877",
        "theme": "Youth Power",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Vile Parle Cha Raja",
        "description": "Educational themed celebrations",
        "address": "Vile Parle East",
        "area": "Vile Parle",
        "location": {"type": "Point", "coordinates": [72.8547, 19.0969]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2616 4455",
        "theme": "Education",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Juhu Cha Raja",
        "description": "Celebrity-visited beach area pandal",
        "address": "Juhu Beach Road",
        "area": "Juhu",
        "location": {"type": "Point", "coordinates": [72.8270, 19.0883]},
        "opening_time": "07:00",
        "closing_time": "23:00",
        "contact": "+91 22 2620 7788",
        "theme": "Celebrity",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Colaba Cha Raja",
        "description": "Tourist-friendly pandal in South Mumbai",
        "address": "Colaba Causeway",
        "area": "Colaba",
        "location": {"type": "Point", "coordinates": [72.8265, 18.9219]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2202 4466",
        "theme": "Tourism",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Marine Lines Cha Raja",
        "description": "Heritage area celebration",
        "address": "Marine Lines Station",
        "area": "Marine Lines",
        "location": {"type": "Point", "coordinates": [72.8258, 18.9432]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2207 5599",
        "theme": "Heritage",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Mahim Cha Raja",
        "description": "Near famous Mahim Dargah",
        "address": "Mahim West",
        "area": "Mahim",
        "location": {"type": "Point", "coordinates": [72.8419, 19.0355]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2445 6677",
        "theme": "Unity in Diversity",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Shivaji Park Cha Raja",
        "description": "Famous for its sports-themed celebrations",
        "address": "Shivaji Park, Dadar",
        "area": "Dadar",
        "location": {"type": "Point", "coordinates": [72.8371, 19.0283]},
        "opening_time": "06:00",
        "closing_time": "22:30",
        "contact": "+91 22 2414 8899",
        "theme": "Sports",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Versova Cha Raja",
        "description": "Beach area pandal with fishing community",
        "address": "Versova Village",
        "area": "Versova",
        "location": {"type": "Point", "coordinates": [72.8182, 19.1311]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2636 5544",
        "theme": "Marine",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Lokhandwala Cha Raja",
        "description": "Celebrity neighborhood celebrations",
        "address": "Lokhandwala Complex, Andheri",
        "area": "Andheri",
        "location": {"type": "Point", "coordinates": [72.8316, 19.1367]},
        "opening_time": "07:00",
        "closing_time": "23:00",
        "contact": "+91 22 2631 7788",
        "theme": "Glamour",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Oshiwara Cha Raja",
        "description": "Television industry supported pandal",
        "address": "Oshiwara, Andheri West",
        "area": "Oshiwara",
        "location": {"type": "Point", "coordinates": [72.8367, 19.1397]},
        "opening_time": "07:00",
        "closing_time": "22:30",
        "contact": "+91 22 2633 9900",
        "theme": "Television",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Jogeshwari Cha Raja",
        "description": "Cave temple inspired celebrations",
        "address": "Jogeshwari East",
        "area": "Jogeshwari",
        "location": {"type": "Point", "coordinates": [72.8497, 19.1367]},
        "opening_time": "06:00",
        "closing_time": "22:00",
        "contact": "+91 22 2678 4455",
        "theme": "Ancient Culture",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Kalina Cha Raja",
        "description": "University area celebrations",
        "address": "Kalina Campus",
        "area": "Kalina",
        "location": {"type": "Point", "coordinates": [72.8675, 19.0717]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2652 3322",
        "theme": "Education",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Dharavi Cha Raja",
        "description": "Asia's largest slum's famous pandal",
        "address": "90 Feet Road, Dharavi",
        "area": "Dharavi",
        "location": {"type": "Point", "coordinates": [72.8552, 19.0380]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2407 6688",
        "theme": "Community Unity",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Sewri Cha Raja",
        "description": "Port area celebrations",
        "address": "Sewri West",
        "area": "Sewri",
        "location": {"type": "Point", "coordinates": [72.8587, 18.9977]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2373 5544",
        "theme": "Maritime",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Marol Cha Raja",
        "description": "MIDC area celebrations",
        "address": "Marol MIDC",
        "area": "Marol",
        "location": {"type": "Point", "coordinates": [72.8789, 19.1107]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2929 7788",
        "theme": "Industry",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Gorai Cha Raja",
        "description": "Beach area eco-friendly celebrations",
        "address": "Gorai Beach Road",
        "area": "Gorai",
        "location": {"type": "Point", "coordinates": [72.7784, 19.2324]},
        "opening_time": "07:00",
        "closing_time": "21:30",
        "contact": "+91 22 2867 4455",
        "theme": "Beach Clean",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Mira Road Cha Raja",
        "description": "Suburban community celebrations",
        "address": "Mira Road East",
        "area": "Mira Road",
        "location": {"type": "Point", "coordinates": [72.8666, 19.2866]},
        "opening_time": "06:30",
        "closing_time": "22:00",
        "contact": "+91 22 2812 3344",
        "theme": "Community",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Bhayander Cha Raja",
        "description": "Known for its grand processions",
        "address": "Bhayander West",
        "area": "Bhayander",
        "location": {"type": "Point", "coordinates": [72.8540, 19.3042]},
        "opening_time": "06:00",
        "closing_time": "22:30",
        "contact": "+91 22 2845 6677",
        "theme": "Procession",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Naigaon Cha Raja",
        "description": "Railway area celebrations",
        "address": "Naigaon East",
        "area": "Naigaon",
        "location": {"type": "Point", "coordinates": [72.8494, 19.3514]},
        "opening_time": "07:00",
        "closing_time": "22:00",
        "contact": "+91 22 2888 9900",
        "theme": "Railways",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Vasai Cha Raja",
        "description": "Historical fort area celebrations",
        "address": "Vasai Fort Road",
        "area": "Vasai",
        "location": {"type": "Point", "coordinates": [72.8150, 19.3919]},
        "opening_time": "06:30",
        "closing_time": "21:30",
        "contact": "+91 22 2889 1122",
        "theme": "History",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Virar Cha Raja",
        "description": "End of Western line celebrations",
        "address": "Virar West",
        "area": "Virar",
        "location": {"type": "Point", "coordinates": [72.8062, 19.4547]},
        "opening_time": "06:00",
        "closing_time": "22:00",
        "contact": "+91 22 2890 3344",
        "theme": "Suburban Life",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Thane Cha Raja",
        "description": "Lake city's main celebration",
        "address": "Thane West",
        "area": "Thane",
        "location": {"type": "Point", "coordinates": [72.9777, 19.2183]},
        "opening_time": "06:00",
        "closing_time": "23:00",
        "contact": "+91 22 2534 5566",
        "theme": "Lake City",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    },
    {
        "name": "Dombivli Cha Raja",
        "description": "Cultural capital celebrations",
        "address": "Dombivli East",
        "area": "Dombivli",
        "location": {"type": "Point", "coordinates": [73.0792, 19.2094]},
        "opening_time": "06:30",
        "closing_time": "22:30",
        "contact": "+91 22 2545 7788",
        "theme": "Culture",
        "idol_type": "Temporary",
        "created_at": datetime.now()
    },
    {
        "name": "Kalyan Cha Raja",
        "description": "Ancient city celebrations",
        "address": "Kalyan West",
        "area": "Kalyan",
        "location": {"type": "Point", "coordinates": [73.1287, 19.2403]},
        "opening_time": "06:00",
        "closing_time": "22:00",
        "contact": "+91 22 2542 9900",
        "theme": "Heritage",
        "idol_type": "Eco-friendly",
        "created_at": datetime.now()
    }
]

# Function to add pandals to database
def add_pandals():
    try:
        # First, create a 2dsphere index on location field if it doesn't exist
        db.pandals.create_index([("location", "2dsphere")])
        
        # Insert all pandals
        result = db.pandals.insert_many(mumbai_pandals)
        print(f"Successfully added {len(result.inserted_ids)} pandals!")
        
        # Verify the count
        total_pandals = db.pandals.count_documents({})
        print(f"Total pandals in database: {total_pandals}")
        
    except Exception as e:
        print(f"An error occurred: {str(e)}")
    finally:
        client.close()

if __name__ == "__main__":
    add_pandals()
